Update Inference in Bayesian Networks.ipynb
pgmpy/pgmpy pull request #1137
Opened 2019-07-04 13:15 UTC by heldmo

### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

### Fixes # .

#### Changes
update the wget command
works under 0.1.7 and python 3.7.

2019-07-04 13:35 UTC, ankurankan commented
@heldmo Does the current code throws any errors?

2019-07-04 13:46 UTC, heldmo commented
> @heldmo Thanks for the PR. Does the current code throw any errors?

I may be misusing the tutorial but simply copy-pasting the code gives me this

```
!wget http://www.bnlearn.com/bnrepository/asia/asia.bif.gz
!gzip -qd asia.bif.gz | rm asia.bif.gz
'wget' is not recognized as an internal or external command,
operable program or batch file.
'gzip' is not recognized as an internal or external command,
operable program or batch file.
```
Thanks for your quick replies!

2019-07-04 13:47 UTC, ankurankan commented
@heldmo Are you using IPython shell or just the normal python shell? Also, are you on windows by any chance?

2019-07-04 13:48 UTC, heldmo commented
@ankurankan I'm using the IPython shell and yes, I am on Windows 10.

2019-07-04 13:58 UTC, ankurankan requested changes
@heldmo That makes sense. I guess you have manually install wget and gzip in windows. But it's better to have it with python. I have added a few comments to your changes. PR looks good otherwise. Thanks.

2019-07-04 13:58 UTC, ankurankan commented on examples/Inference in Bayesian Networks.ipynb
> +    "f=wget.download('http://www.bnlearn.com/bnrepository/asia/asia.bif.gz')",
We follow PEP8 for our code. So, please add space before and after the `=`.

2019-07-04 13:58 UTC, ankurankan commented on examples/Inference in Bayesian Networks.ipynb
> +    "f = gzip.open('asia.bif.gz', mode='rb')"
You can use the `with` statement to open the file so that you don't need to close the file explicitly. Will make the code cleaner.

2019-07-04 13:58 UTC, ankurankan commented on examples/Inference in Bayesian Networks.ipynb
> +    "f= open('asia.bif', mode='wb')"
Same as the last comment. Can use `with` here.

2019-07-04 14:25 UTC, ankurankan approved these changes

2019-07-05 09:35 UTC, merged

2019-07-05 09:36 UTC, ankurankan commented
@heldmo Thanks for the PR.