Hotfix/spell check
pgmpy/pgmpy pull request #1562
Opened 2022-08-10 19:06 UTC by mstill3

### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.

### Issue number(s) that this pull request fixes
- Fixes #

### List of changes to the codebase in this pull request
- 
-
-

2022-08-11 05:51 UTC, ankurankan requested changes
Thanks a lot for the PR, this fixes a lot of typos. I have added a few comments where I think we shouldn't change the current text.

2022-08-11 05:51 UTC, ankurankan commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Check the commits or even all commits' message styles matches our requested structure.
This doesn't seem correct to me.

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/PC.py
> +                    discovery with multicore PCs." IEEE/ACM transactions on computational
I wouldn't change this. The paper title actually uses `multi-core`.

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/StructureScore.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
I would keep this as dtype as I think it is more precise.

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/StructureScore.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/StructureScore.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/StructureScore.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/StructureScore.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/base.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/estimators/base.py
> +            Note that pandas converts each column containing `numpy.NaN`s to datatype `float`.)
Same

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/factors/discrete/JointProbabilityDistribution.py
> +                    raise TypeError("Event 3 should be a 1d list of strings")
I would rather change this to `event3` so that it matches the argument name.

2022-08-11 05:51 UTC, ankurankan commented on pgmpy/tests/test_estimators/test_PC.py
> +# high dimensional causal discovery with multicore PCs." IEEE/ACM transactions
Wouldn't change here either.

2022-08-21 00:08 UTC, mstill3 commented
@ankurankan Thank you for reviewing it! I made all the suggestions to the wording in the latest commit.

2022-08-21 07:01 UTC, ankurankan commented
@mstill3 Thanks for the changes, looks good now :)

2022-08-21 07:01 UTC, merged