Updated docstring for get_cpds method in BayesianNetwork
pgmpy/pgmpy pull request #1835
Opened 2024-10-13 10:02 UTC by B3CODER

### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

 Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
 Make sure you are making a pull request against the dev branch (left side). Also you should start your branch off our dev.
 Check the commit's or even all commits' message styles matches our requested structure.

- Fixes #933

### List of changes to the codebase in this pull request
- Updated the docstring for the get_cpds method in BayesianNetwork to clarify the method's behavior when the node argument is specified and when it is not.
- Added more detailed descriptions to improve the documentation's clarity and usefulness for users.

2024-10-13 10:16 UTC, ankurankan requested changes
@B3CODER Thanks for creating the PR. I have added a few small comments to the changes.

2024-10-13 10:16 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        - If 'node' is specified:
I would keep the first line in the form of `name : type` form. Have a look at the numpydoc style for details: https://numpydoc.readthedocs.io/en/latest/format.html#returns

2024-10-13 10:16 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
>          >>> from pgmpy.models import BayesianNetwork
I would completely switch out this example with something similar to the `get_example_model` example I had added to the issue.

2024-10-13 14:53 UTC, ankurankan requested changes

2024-10-13 14:53 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +
Could you please update the examples here such that we use one of the example models? If you search for `get_example_model`, you will find plenty of docstring examples using the `get_example_model` method to create a model.

2024-10-13 18:37 UTC, B3CODER commented
### Changes Made:
- Updated the `get_cpds` method to provide consistent output for both the list of all CPDs and the CPD of a specific node.
- Added error handling for nodes not present in the model.

### Screenshot of the modified code:
![image](https://github.com/user-attachments/assets/518ca3a2-3e7e-4181-ba02-cb40f088208f)

2024-10-14 06:45 UTC, ankurankan requested changes

2024-10-14 06:45 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        >>> random_model = BayesianNetwork.get_random(n_nodes=8, edge_prob=0.4, n_states=2, latents=True)
@B3CODER Here, you are currently using the `get_random` method to generate the model. I was suggesting to use the `get_example_model` method to generate the model. Something like this:
```python
from pgmpy.utils import get_example_model
model = get_example_model('cancer')
```
And then show examples similar to the ones that you have shown here.

2024-10-14 06:45 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        >>> model = ('alarm')
You would need to revert this.

2024-10-14 06:45 UTC, ankurankan commented on pgmpy/utils/utils.py
> +    >>> model = (model='asia')
This as well.

2024-10-14 06:48 UTC, ankurankan commented
@B3CODER 

> Updated the get_cpds method to provide consistent output for both the list of all CPDs and the CPD of a specific node.
> Added error handling for nodes not present in the model.

I do not see any changes related to these in the PR. Have you pushed your local changes? Also, I would not make those changes as it would break a lot of other parts of the codebase.

2024-10-14 12:43 UTC, ankurankan commented
@B3CODER The code formatting changes were needed only for the files that you had changes in, not for the whole repo. You can revert these by running:
```
git revert d31ba54
```

2024-10-14 12:46 UTC, ankurankan requested changes
I have left a few comments, everything else looks good.

2024-10-14 12:46 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        >>> cpds=model.get_cpds()
Space before and after `=`. Should be: `cpds = model.get_cpds()`

2024-10-14 12:46 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        >>>  cpds = model.get_cpds('bronc')     # Returns the CPD of node
Change cpds to cpd as we expect the method to only return a single cpd

2024-10-14 12:46 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        >>> cpds = model.get_cpds('tbu')
You can remove this example with the error.

2024-10-16 09:12 UTC, ankurankan commented
@B3CODER This PR can be closed. Right?

2024-10-16 09:19 UTC, B3CODER commented
Yes sir

On Wed, 16 Oct 2024, 2:43 pm Ankur Ankan, ***@***.***> wrote:

> @B3CODER <https://github.com/B3CODER> This PR can be closed. Right?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pgmpy/pgmpy/pull/1835#issuecomment-2416201944>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZA3LWF557PYPV3FABGKBLZ3YU3BAVCNFSM6AAAAABP3I7ETOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMJWGIYDCOJUGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-16 09:33 UTC, B3CODER commented
Sir, any issue regarding PR?

On Wed, 16 Oct 2024 at 14:49, BHAVYA SHAH ***@***.***> wrote:

> Yes sir
>
> On Wed, 16 Oct 2024, 2:43 pm Ankur Ankan, ***@***.***>
> wrote:
>
>> @B3CODER <https://github.com/B3CODER> This PR can be closed. Right?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pgmpy/pgmpy/pull/1835#issuecomment-2416201944>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVZA3LWF557PYPV3FABGKBLZ3YU3BAVCNFSM6AAAAABP3I7ETOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMJWGIYDCOJUGQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-10-16 09:38 UTC, closed without merging