Feature/missing samples
pgmpy/pgmpy pull request #1850
Opened 2024-10-22 11:51 UTC by Nuna7

Issue #1736

1. Add functionality to simulate missing values for BayesianNetwork.
2. Add test cases for the new feature
3. Add relative tolerance for test case, test_connected_predict_probability, in test_BayesianModel.py

2024-10-22 12:51 UTC, ankurankan commented
@Nuna7 Thanks for the PR. This issue has turned out to be much more complicated than I had originally thought when creating the issue. I have just added a reference in the issue to the paper discussing different types of missingness using DAGs. I think your current implementation covers the MCAR (missing completely at random) case, so should still be useful. For the other cases, I think we will need to first figure out how to represent those.

2024-10-22 13:03 UTC, ankurankan requested changes
The PR looks good to me. I have added a few minor comments.

2024-10-22 13:03 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        Simulation with missing values:
Could you please move the example to the `Examples` section in the docstring.

2024-10-22 13:03 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +            mask = np.random.rand(*samples.shape)
Could you use numpy's generator interface here (https://numpy.org/doc/stable/reference/random/generator.html) ? And also set a seed value if passed in the argument, to make this reproducible over multiple runs.

2024-10-22 13:03 UTC, ankurankan commented on pgmpy/models/BayesianNetwork.py
> +        missing_columns: list
Please specify the default values here.

2024-10-22 13:03 UTC, ankurankan commented on pgmpy/tests/test_sampling/test_Sampling.py
> +    def test_missing_scheme_sample(self):
Could you move this test to the `test_BayesianNetworks.py` file as the feature is implemented in BayesianNetwork.py?

2024-10-22 14:34 UTC, ankurankan commented
@Nuna7 BTW you can install a pre-commit hook to automatically fix all code formatting when committing. From the pgmpy dir, you can run:
```
pip install pre-commit
pre-commit install
```

2024-10-22 14:41 UTC, Nuna7 commented
> @Nuna7 BTW you can install a pre-commit hook to automatically fix all code formatting when committing. From the pgmpy dir, you can run:
> 
> ```
> pip install pre-commit
> pre-commit install
> ```

2024-10-23 12:51 UTC, ankurankan commented
@Nuna7 Any reason for closing this? I thought this was mostly ready to be merged.

2024-10-23 14:21 UTC, Nuna7 commented
@ankurankan Initially, I thought you closed it (being a beginner in git) and just now I realized that I may mistakenly closed it.

2024-10-24 06:21 UTC, ankurankan approved these changes

2024-10-24 06:22 UTC, merged

2024-10-24 06:22 UTC, ankurankan commented
@Nuna7 Thanks for the PR :)