Issue/1787 add continuous variable models updated
pgmpy/pgmpy pull request #1852
Opened 2024-10-24 19:14 UTC by B3CODER

### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.

### Issue number(s) that this pull request fixes
- Fixes #1787 

### List of changes to the codebase in this pull request
- Updated CPD construction for model handling:
Modified the code in pgmpy/utils/utils.py to handle the distinction between categorical and continuous models more clearly by introducing predefined sets of models.
The new structure uses cat_models and cont_models variables to classify models and select the correct processing method based on whether the model is categorical or continuous.

-Updated model handling logic in utils.py:
Previous logic was based solely on file extensions (e.g., ".bif.gz"), which was insufficient.
Introduced new logic to check the model type based on predefined lists of cat_models and cont_models.
Raised a custom error if the model is not found in either set.

-Added tests to test_utils.py:

Added unit tests in pgmpy/tests/test_utils/test_utils.py to verify that both categorical and continuous models are being handled correctly.
Tests include:
Verifying that known categorical models are processed correctly.
Verifying that known continuous models are processed correctly.

2024-10-25 07:40 UTC, ankurankan commented
@B3CODER The PR looks good to me. Can you add the Json files for other gaussian models?

2024-10-26 04:00 UTC, B3CODER commented
Certainly, I'd be happy to add the JSON files for the other Gaussian models.

On Fri, 25 Oct 2024 at 13:10, Ankur Ankan ***@***.***> wrote:

> @B3CODER <https://github.com/B3CODER> The PR looks good to me. Can you
> add the Json files for other gaussian models?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pgmpy/pgmpy/pull/1852#issuecomment-2437108848>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZA3LW72RJZO4LTRTFR4A3Z5HYWNAVCNFSM6AAAAABQRYLFZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZXGEYDQOBUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-26 11:50 UTC, B3CODER commented
Hello,
Just small question you just requested to close the issue.

I have little confusion about that.

On Sat, 26 Oct 2024, 9:30 am BHAVYA SHAH, ***@***.***> wrote:

> Certainly, I'd be happy to add the JSON files for the other Gaussian
> models.
>
> On Fri, 25 Oct 2024 at 13:10, Ankur Ankan ***@***.***>
> wrote:
>
>> @B3CODER <https://github.com/B3CODER> The PR looks good to me. Can you
>> add the Json files for other gaussian models?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pgmpy/pgmpy/pull/1852#issuecomment-2437108848>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVZA3LW72RJZO4LTRTFR4A3Z5HYWNAVCNFSM6AAAAABQRYLFZGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZXGEYDQOBUHA>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-10-26 11:55 UTC, ankurankan commented
@B3CODER To clarify, I thought #1849 and #1852 are duplicates as both of them seem to implement the same feature. Hence, I wanted to check which branch you plan to continue adding the new models to? And I would close the other.

2024-10-26 12:21 UTC, B3CODER commented
No, I did changes as per your request in new one

2024-10-26 12:28 UTC, ankurankan commented
Okay, but you don't need to create new PRs for changes. You can keep adding commits to the same one, which makes it easier to track new changes. And with duplicated PR I mean that all the changes that you have in this PR is also in the other PR, hence if we merge this one, the other would not be needed. Both the PRs address the same changes, and this is the updated version compared to the other.

2024-10-26 12:58 UTC, B3CODER commented
Okay,  understood and yes this is the updated one.

2024-11-01 16:19 UTC, ankurankan requested changes
Have added couple of minor comments but looks good to me otherwise.

2024-11-01 16:19 UTC, ankurankan commented on model.bif
> +network unknown {
What is this file used for?

2024-11-01 16:19 UTC, ankurankan commented on pgmpy/utils/utils.py
> +        # Handle reading of continuous models
We don't need this if statement. Because it's only continuous model, it will always be a JSON.

2024-11-12 00:15 UTC, ankurankan commented
@B3CODER Sorry for the delay on this. I think I found a minor mistake in the current JSON file format that you are using. The `variance` values are currently a list but the variance would always be a float value. Because of this, we get an error when we try to print the CPD, for example:
```python
In [9]: model = get_example_model('ecoli70')                                                  
                                                                                              
In [10]: model.cpds 
```
Could you please update the JSON files?

2024-11-22 10:18 UTC, merged