Add ExpertKnowledge support for PC algorithm
pgmpy/pgmpy pull request #1887
Opened 2024-12-18 17:30 UTC by Nimish-4

### Your checklist for this pull request
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.

### Changes up for discussion - 
1. Implementing checks like these, as [highlighted in previous PR](https://github.com/pgmpy/pgmpy/pull/1813/commits/c315fd2f9012c753fe9cb25814edc899c8b5a09c#diff-21d6ba646ed3ffcff694dbcec44c92fe40c2b7717f8bf14755127e8ba3bdbc89R194).
2. Changing test cases, as [highlighted in the previous PR](https://github.com/pgmpy/pgmpy/pull/1813/commits/e206132b41d736bdde4b56ff7027854cd09abb5e). Looks like they were implemented to reduce sample size/time taken for testing PC.

2024-12-18 17:32 UTC, Nimish-4 commented
I also have a doubt about integration of expert knowledge with PC. Imagine the user passes only one fixed edge to PC, say (u,v). Since there would be no white list, we consider all edges in initial graph. [This part of the algorithm](https://github.com/pgmpy/pgmpy/pull/1887/files#diff-21d6ba646ed3ffcff694dbcec44c92fe40c2b7717f8bf14755127e8ba3bdbc89R299) means that both (u,v) and (v,u) would remain in the graph instead of just (u,v). Basically, this integration of fixed edges does not seem to be present currently, unless I misunderstood something.

2024-12-19 04:47 UTC, ankurankan commented
@Nimish-4 The PC algorithm starts with an undirected graph, removes edges from it, and then tries to orient the edges to make the final graph directed. Currently, the changes that you have made is for the first part of the algorithm. We would also need to make changes to the skeleton_to_pdag method: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/PC.py#L372. For fixed_edges we would need to first orient the edges as provided by fixed_edges, and then let the other orientation rules work after that.

2024-12-19 04:51 UTC, ankurankan commented on pgmpy/estimators/PC.py
>          max_cond_vars=5,
I would suggest moving `max_cond_vars` to ExpertKnowledge as well.

2024-12-24 16:00 UTC, ankurankan requested changes
Mostly looks good to me. I haven't tried to run any of the code yet. Is the PR ready or any other changes still need to be made?

2024-12-24 16:00 UTC, ankurankan commented on pgmpy/estimators/PC.py
> +        expert_knowledge=None,
I would suggest moving this argument after `variant` as the others are more commonly used and more important.

2024-12-24 16:00 UTC, ankurankan commented on pgmpy/estimators/ExpertKnowledge.py
> +            independce tests (e.g. Peter Clark algorithm). Default: 5
I would suggest using PC algorithm everywhere instead of Peter Clark. I don't think most users would know the full name.

2024-12-24 17:20 UTC, Nimish-4 commented
> Mostly looks good to me. I haven't tried to run any of the code yet. Is the PR ready or any other changes still need to be made?

I'm still reading up on this a little bit and completing the requested changes. Beyond that I think its fine. Maybe 1 or 2 days to finalize.

2025-01-08 13:13 UTC, closed without merging