Implement Functional CPD
pgmpy/pgmpy pull request #1888
Opened 2024-12-18 18:31 UTC by Nuna7

@ankurankan I kind of forgot the desired structure and functionality 😅. So please review and mention any changes necessary.

2024-12-19 04:53 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        fn: callable
I prefer adding empty lines between each argument. I think it makes it cleaner and easier to read.

2024-12-19 04:55 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        # For P(Y| X1, X2) = N(0.2x1 + 0.3x2 + 1.0; 1)
There's a typo here. The variable here is `Y` but the variable in the example below is `X3`

2024-12-19 04:55 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +            variable="x3",
New code lines in docstring needs to be started with `...`; otherwise it wouldn't parse correctly for online documentation.

2024-12-19 05:12 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +    def sample(self, parent_sample=None):
I would change this function to accept a `n_samples` argument and accept `parent_sample` as a dataframe object. In the broader context, the user would have a Bayesian Network with FunctionalCPD associated with each of the nodes. They would then sample from this network, which would translate into calling this `sample` function for each of these FunctionalCPDs.

2024-12-19 05:16 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +                f"FunctionalCPD(variable={self.variable}, "
I would change this to something similar to TabularCPD and LinearGaussianCPD.

2024-12-19 05:17 UTC, ankurankan commented
@Nuna7 This is kind of what I was thinking as well. The next thing to do would be to create a `FunctionalBayesianNetwork` class similar to BayesianNetwork and LinearGaussianBayesianNetwork that can accept Functional CPDs.

2024-12-21 08:50 UTC, Nuna7 commented
@ankurankan Please review and proposed any changes necessary.

2024-12-22 07:11 UTC, ankurankan commented
@Nuna7 I had a quick look at the PR and overall it looks good to me. There are a few minor things that I will put comments for once I get a chance to look into it in a bit more detail. In the meanwhile, if you would like you can start working on using pyro functions in FunctionalCPD. If you work on that I would also suggest creating another branch off this PR's branch, so that we can merge this PR independent on the pyro stuff.

2024-12-24 10:27 UTC, ankurankan requested changes
@Nuna7 I have added a few minor comments. Looks good to me otherwise.

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        """
Missing class description.

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +    def __init__(self, variable, fn, parents=None):
Wouldn't setting the default to `parents=[]` be easier?

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        >>> from pgmpy.factors.hybrid import LinearGaussianCPD
Should this be FunctionalCPD?

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        >>> from pgmpy.factors.hybrid.FunctionalCPD import FunctionalCPD
This should work with just `from pgmpy.factors.hybrid import FunctionalCPD`.

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +        fn_name = "f(mean, std)" if self.fn.__name__ == "<lambda>" else self.fn.__name__
I would just leave the name to `lambda` or something as `f(mean, std)` is confusing.

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/models/FunctionalBayesianNetwork.py
> +        >>> from pgmpy.models.FunctionalBayesianNetwork import FunctionalBayesianNetwork
Same here should be able to import `from pgmpy.factors.hybrid` and `pgmpy.models`

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/models/FunctionalBayesianNetwork.py
> +        >>> from pgmpy.models.FunctionalBayesianNetwork import FunctionalBayesianNetwork
Same as above

2024-12-24 10:27 UTC, ankurankan commented on pgmpy/tests/test_factors/test_hybrid/test_Functional_CPD.py
> +from pgmpy.models.LinearGaussianBayesianNetwork import LinearGaussianBayesianNetwork
Same as above.

2024-12-25 09:15 UTC, Nuna7 commented
@ankurankan Sorry, I forget to make a new branch for change to using pyro functions. When I make the required changes suggest, I already made change to using pyro functions and add both simultaneously and latter forget that the change in the sampling function such as iterating using iterrows should be for another branch where change to pyro should be implemented. So I just push the test case as well to current branch.

2025-01-10 11:42 UTC, ankurankan requested changes
@Nuna7 I have added a few minor comments but overall looks good to me.

2025-01-10 11:42 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +    where the distributio to represented is defined by function (input as parameter) which calls pyro.sample function.
Typo: `distributio` -> `distribution`

2025-01-10 11:42 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +            for _, row in parent_sample.iterrows():
Iteratively making a function call can be quite slow when generating a lot of samples. I think we should give the user an option to specify the function in vectorized form. We could possibly add an argument to the `__init__` method for the user to specify whether the function is vectorized or not. Using that argument/flag we can make the choice here whether we should do an iterative function call (maybe parallelly) or do a vectorized function call. But lets keep this change for later. Can you please create an issue about it?

2025-01-10 11:42 UTC, ankurankan commented on pgmpy/factors/hybrid/FunctionalCPD.py
> +            "lambda(mean, std)" if self.fn.__name__ == "<lambda>" else self.fn.__name__
When the function is lambda, let's just leave it to `"lambda fun."`. `mean` and `std` don't add any information and might not be relevant for some distributions.

2025-01-10 11:42 UTC, ankurankan commented on pgmpy/models/FunctionalBayesianNetwork.py
> +                    break
Should this be `continue`? `break` would exit out of the `for cpd in cpds` loop.

2025-01-12 12:40 UTC, ankurankan commented on pgmpy/models/FunctionalBayesianNetwork.py
> +                    break
Misunderstood the code flow here. Looks fine.

2025-01-12 12:50 UTC, merged