Doc fix reflecting change in directory structure.
pgmpy/pgmpy pull request #747
Opened 2016-09-15 10:17 UTC by sudk1896

The example in ```README.md``` uses the old directory structure. This PR corrects it.
```from pgmpy.factors import TabularCPD```

to

```from pgmpy.factors.discrete import TabularCPD```

Also, the installation instructions, use python3 to install. In my opinion, this is a bit confusing. Most distros ship with ```python2.7.x``` as default. we should instead do
```sudo python setup.py install```
and explicitly tell the user to do ```python3``` if they want to install it for python3.
@ankurankan Review.

2016-09-15 12:50 UTC, khalibartan commented on README.md
>  python3
Change this line too.

2016-09-17 07:20 UTC, ankurankan commented on README.md
>  python3
@khalibartan @sudk1896 I think it's just in the wrong place. Line 116 should be ```python.

2016-09-17 07:20 UTC, ankurankan commented on README.md
>  python3
@khalibartan @sudk1896 I think it's just in the wrong place. Line 116 should be ```python.

2016-09-17 07:20 UTC, ankurankan requested changes

2016-10-05 12:02 UTC, merged