Pr#774
pgmpy/pgmpy pull request #781
Opened 2016-12-12 15:43 UTC by kris-singh

2016-12-12 17:17 UTC, ankurankan commented
@kris-singh Tests are failing. Please fix them.

2016-12-12 17:33 UTC, khalibartan commented
@kris-singh Re-label the PR to something related to context of the problem which PR solves.

2016-12-13 08:14 UTC, ankurankan commented
@khalibartan @kris-singh @yashu-seth I am having second thoughts about this implementation. It will get too complicated and nested when we have a lot of distributions. I have created a new issue #782 for discussing a possible new architecture.

2016-12-13 11:04 UTC, ankurankan requested changes

2016-12-13 11:04 UTC, ankurankan commented on pgmpy/factors/continuous/ContinuousFactor.py
> +import scipy
@kris-singh Do we need both of these import statements?

2016-12-13 11:06 UTC, ankurankan commented
@kris-singh We would like to have to code according to the new architecture that we discussed in #782. So closing this.

2016-12-13 11:06 UTC, closed without merging