Markov Chain accepts matrix PR#748
pgmpy/pgmpy pull request #788
Opened 2016-12-17 08:42 UTC by kris-singh

2016-12-17 09:23 UTC, kris-singh commented
All nose-test cases are passing for me. I don't understand the errors. Can anyone help

2016-12-17 09:35 UTC, ankurankan commented
@kris-singh You haven't imported numpy in the test file. It shouldn't pass on your local machine also.

2016-12-17 15:38 UTC, khalibartan commented
@kris-singh Can you remove the .pgmx file from the commit? It is not recommended to use `git add .` while adding the files for commit.I guess you might have used it.

2016-12-17 16:41 UTC, kris-singh commented
@khalibartan yes i will do it right now

2016-12-17 21:06 UTC, ankurankan requested changes

2016-12-17 21:06 UTC, ankurankan commented on pgmpy/models/MarkovChain.py
> +        if not isinstance(transition_model, dict) and not isinstance(transition_model, np.ndarray):
@kris-singh Add a statement to convert `transition_model` to a numpy array in the case when the user passes a 2-D list.

2016-12-17 21:06 UTC, ankurankan commented on pgmpy/models/MarkovChain.py
> +            raise ValueError('Dimension mismatch{d1}!={d2}'.format(d1=transition_model.shape[0], d2=transition_model[1]))
@kris-singh Much cleaner if-else would be:
```python
if not dict:
    if not array:
         raise
   elif shape:
         raise
   elif shape = sh:
        raise
```

2016-12-17 21:06 UTC, ankurankan commented on pgmpy/tests/test_models/test_MarkovChain.py
> +
@kris-singh Blank line has spaces.

2016-12-17 21:07 UTC, ankurankan commented
@khalibartan @yashu-seth Can you please review this also ? @kris-singh Can you please merge all your commits into a single commit ?

2016-12-17 21:15 UTC, ankurankan commented
@kris-singh Since you are working with Markov Chains, I think you might also want to have a look at #789.

2016-12-18 05:16 UTC, khalibartan commented on pgmpy/models/MarkovChain.py
> +            raise ValueError('Must be 2d array')
@kris-singh IMO this error is a bit ambiguous. I think something like `Transition model must be a 2d array like object` should be better. The current error doesn't link it to transition model. Please change that.

2016-12-18 05:18 UTC, khalibartan commented on pgmpy/models/MarkovChain.py
> +            raise ValueError('Must be 2d array')
@kris-singh IMO this error is a bit ambiguous. I think something like Transition model must be a 2d array like object should be better. The current error doesn't link it to transition model. Please change that.

2016-12-18 07:36 UTC, yashu-seth requested changes

2016-12-18 07:36 UTC, yashu-seth commented on pgmpy/models/MarkovChain.py
> +            transition_model = dict((i,dict((j, float(transition_model[i][j]))\
@kris-singh PEP8
missing whitespace after ','
the backslash is redundant between brackets

2016-12-18 07:36 UTC, yashu-seth commented on pgmpy/tests/test_models/test_MarkovChain.py
> +        #check for square dimension of the matrix
@kris-singh PEP8 block comment should start with '# '

2016-12-18 11:08 UTC, kris-singh commented
Sorry i made a very silly mistake using squash and had to revert back and then commit :) thats why all the coverall comments.

2016-12-19 08:51 UTC, ankurankan requested changes

2016-12-19 08:51 UTC, ankurankan commented on pgmpy/models/MarkovChain.py
> +        if isinstance(transition_model, np.ndarray):
@kris-singh Can't we put this condition also in the above checks?

2016-12-19 08:51 UTC, ankurankan commented on pgmpy/models/MarkovChain.py
> +        transition_model: dict or ndarray
@kris-singh  Add a more detailed description for the parameter explaining what kind of matrix or dict is expected.

2016-12-20 06:17 UTC, kris-singh commented on pgmpy/models/MarkovChain.py
> +        transition_model: dict or ndarray
I think this line only tells the type of object that is expected which in this case is dict,2d-array.
so i think i could replace this with
transition_model: dict or 2d-array
The next line provides the description which i thik is apt

2016-12-20 07:10 UTC, ankurankan requested changes

2016-12-20 07:10 UTC, ankurankan commented on pgmpy/models/MarkovChain.py
> +        transition_model: dict or ndarray
@kris-singh I think this line should mention about 2-D array. And the description should mention the structure of the dict or array that we are expecting. Check other parts of the code for examples.

2016-12-21 21:22 UTC, kris-singh commented
@ankurankan @khalibartan can you review this guys.

2016-12-22 10:43 UTC, ankurankan approved these changes

2016-12-22 10:43 UTC, merged