Modified docstring of NaiveBayes.local_independencies
pgmpy/pgmpy pull request #806
Opened 2016-12-25 05:50 UTC by raghavg7796

Sorry! I forgot to update the docstring of the method.

2016-12-25 08:42 UTC, raghavg7796 commented
Edited only docstring...still showing failed test

2016-12-26 18:10 UTC, ankurankan requested changes

2016-12-26 18:10 UTC, ankurankan commented on pgmpy/models/NaiveBayes.py
> +        Returns a independencies object containing the local independencies
@raghavg7796 I would suggest you to use something like this: `Returns an instance of Independencies`. Feels technically more correct.

2016-12-27 19:23 UTC, ankurankan approved these changes

2016-12-27 19:27 UTC, merged