FactorGraph: Added copy method
pgmpy/pgmpy pull request #839
Opened 2017-02-06 11:30 UTC by lohani2280

Fixes https://github.com/pgmpy/pgmpy/issues/489

2017-02-06 17:19 UTC, ankurankan requested changes
Seems fine except for the minor issues I have put in comments.

2017-02-06 17:19 UTC, ankurankan commented on pgmpy/models/FactorGraph.py
> +        clone_FactorGraph = FactorGraph(self.edges())
@lohani2280 We use `lower_case_with_underscores` naming convention. So, please change the variable name here.

2017-02-06 17:19 UTC, ankurankan commented on pgmpy/models/FactorGraph.py
> +        >>> from pgmpy.models import FactorGraph
@lohani2280 Import order should be (PEP 8): 
1. standard library imports
2. related third party imports
3. local application/library specific imports

2017-02-06 17:19 UTC, ankurankan commented on pgmpy/models/FactorGraph.py
> +        FactorGraph : Copy of FactorGraph
@lohani2280 `Copy of the FactorGraph instance` is a bit more clearer.

2017-02-06 17:19 UTC, ankurankan commented on pgmpy/tests/test_models/test_FactorGraph.py
> +        phi2 = DiscreteFactor(['b', 'c'], [2, 2], np.random.rand(4))
@lohani2280 I am seeing these 2 statements repeated elsewhere in this class. Can you please move all of them to the `setUp` method. Also make sure to put that in a separate commit.

2017-02-07 11:19 UTC, lohani2280 commented
@ankurankan Thanks for your review. I will make the changes as per your comments and synchronize my PR very soon :)

2017-02-07 11:34 UTC, lohani2280 commented on pgmpy/models/FactorGraph.py
> +        >>> from pgmpy.models import FactorGraph
@ankurankan Sorry , but can you please tell me what's wrong here as i have observed many similar import statements and cannot identify what is wrong.

2017-02-07 12:00 UTC, lohani2280 commented on pgmpy/tests/test_models/test_FactorGraph.py
> +        phi2 = DiscreteFactor(['b', 'c'], [2, 2], np.random.rand(4))
@ankurankan  These two statements are present at many places but its not same everywhere . I mean if you see these in every method of the class , you will observe that there are places where the arguments are a bit different . Please correct me if i am wrong.

2017-02-07 13:40 UTC, ankurankan requested changes

2017-02-07 13:40 UTC, ankurankan commented on pgmpy/models/FactorGraph.py
> +        >>> from pgmpy.models import FactorGraph
@lohani2280 The imports should be in this order:
```python
import numpy as np
from pgmpy.models import FactorGraph
from pgmpy.factors.discrete import DiscreteFactor
```

2017-02-07 13:40 UTC, ankurankan commented on pgmpy/tests/test_models/test_FactorGraph.py
> +        phi2 = DiscreteFactor(['b', 'c'], [2, 2], np.random.rand(4))
@lohani2280 For example we have the same statements in line 255 and 256, 237 and 238, 224 and 225.

2017-02-15 17:38 UTC, merged