Feature/structure search score cache
pgmpy/pgmpy pull request #976
Opened 2018-02-20 08:32 UTC by julianreichinger

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **dev branch** (left side). Also you should start *your branch* off *our dev*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

#### Changes
Please list the proposed changes in this pull request.
- Wrapper class for StructureScore instances with a dynamically sized cache for local scores

💔Thank you!

2018-02-22 09:29 UTC, ankurankan commented
@julianreichinger Thanks a lot for the PR. But one of the tests is failing on python 2.7: https://travis-ci.org/pgmpy/pgmpy/jobs/343734794#L845. And it's because python 2.7 doesn't have `unittest.mock`, and for dealing with that we use the mock module: https://mock.readthedocs.io/en/latest/. Could you please fix the tests (can either have a try except in imports or just replace with the mock module) ?

2018-02-22 12:03 UTC, julianreichinger commented
@ankurankan Tests are fixed, I replaced the unittest.mock package.

2018-02-26 17:47 UTC, ankurankan requested changes
@julianreichinger Sorry for the late reply. The PR looks good except for one minor comment that I have put. Also, could you please merge all your commits into a single commit using `git rebase`. That will help us in keeping our git history clean.

2018-02-26 17:47 UTC, ankurankan commented on pgmpy/estimators/ScoreCache.py
> +        :param base_scorer: Instance of type StructureScore
@julianreichinger We use numpy style doctests. So, it should be something like:
```
base_scorer: StructureScore instance
```

2018-02-27 09:31 UTC, julianreichinger commented
@ankurankan I made the change you requested and squashed the commits. Actually I have never done that before but it is nice to finally learn my way around Git.

2018-02-27 10:04 UTC, ankurankan commented on pgmpy/estimators/ScoreCache.py
> +        :param base_scorer: StructureScore instance
@julianreichinger This still doesn't seem right. I am sorry for not being clearer in my last comment. You will need to remove the `:param` from the front for numpy style docstring. You can also have a look at it in more detail here: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html.

2018-02-27 11:28 UTC, julianreichinger commented
@ankurankan Sorry, I misunderstood what you meant. I read through the numpy examples and changed the docstrings accordingly. Hopefully everything should be correct now.

2018-03-07 09:44 UTC, julianreichinger commented
@ankurankan Any update?

2018-03-08 08:11 UTC, ankurankan commented
@julianreichinger Looks good. Merging. Sorry for the delay.

2018-03-08 08:11 UTC, ankurankan approved these changes

2018-03-08 08:12 UTC, merged